# Generated by Django 3.0.8 on 2020-10-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='meal_text',
        ),
        migrations.RemoveField(
            model_name='price',
            name='votes',
        ),
        migrations.AddField(
            model_name='price',
            name='price_text',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
    ]
